---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubeconfig.choclab.net
  resources:
  - clusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubeconfig.choclab.net
  resources:
  - clusters/finalizers
  verbs:
  - update
- apiGroups:
  - kubeconfig.choclab.net
  resources:
  - clusters/status
  verbs:
  - get
  - patch
  - update
