kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: management-cluster
nodes:
- role: control-plane
  extraMounts:
  - hostPath: /home/mproffitt/.kube/config
    containerPath: /tmp/kubeconfig
  labels:
    kubeconfig.choclab.net/operator: allow
  kubeadmConfigPatches:
  - |
    apiVersion: kubeadm.k8s.io/v1beta3
    kind: ClusterConfiguration
    apiServer:
      certSANs:
      - "192.168.1.2"
      - "127.0.0.1"
- role: worker
- role: worker