apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: podinfo
  namespace: cluster-kind-tenant1
spec:
  interval: 1m
  url: https://stefanprodan.github.io/podinfo
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: cluster-kind-tenant1
spec:
  interval: 10m
  chart:
    spec:
      chart: podinfo
      version: '6.5.*'
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: cluster-kind-tenant1
      interval: 10m
  values:
    replicaCount: 2
  kubeConfig:
    secretRef:
      name: kind-tenant1-kubeconfig
  targetNamespace: default
  storageNamespace: default
  install:
    createNamespace: true